feat(DNA-3221): Disabled actions for non-owners
careem/superset pull request #150
Opened 2023-04-05 19:25 UTC by SamraHanifCareem

- [ ] Disable edit and delete actions for non-owners in Dashboard.
- [ ] Display relevant message in tooltip while actions being disabled.

2023-04-06 10:00 UTC, puneet-bdp requested changes

2023-04-06 10:00 UTC, puneet-bdp commented on superset-frontend/src/views/CRUD/dashboard/DashboardList.tsx
> +  .disabled {
We are disabling it from JS only? Can user still change this on UI and edit the dashboard?

2023-04-06 10:00 UTC, puneet-bdp commented on superset-frontend/src/views/CRUD/dashboard/DashboardList.tsx
> +  .disabled {
I mean it's not disabled from backend.

2023-04-06 10:46 UTC, puneet-bdp commented on superset-frontend/src/views/CRUD/dashboard/DashboardList.tsx
> +  .disabled {
Yes.. I mean shouldn't we put this restriction at backend as well?

2023-04-06 15:55 UTC, SamraHanifCareem commented on superset-frontend/src/views/CRUD/dashboard/DashboardList.tsx
> +  .disabled {
No, so we catch the owners from backend and check if the owners exist there. If not, we disable the button.
Thats whats is happening every where throughout the application

2023-04-07 12:09 UTC, puneet-bdp approved these changes

2023-04-11 00:09 UTC, merged