feat(BDP-4801): View Flash Object Information
careem/superset pull request #75
Opened 2022-09-22 11:46 UTC by SamraHanifCareem

feat(BDP-4801): View Flash Object Information

### SUMMARY
1- Action button visibility on Flash Management Module.
2- Opening draggable View Flash Modal on action trigger
3- Displaying all the flash object details briefly

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

<img width="1791" alt="Screenshot 2022-09-22 at 4 44 42 PM" src="https://user-images.githubusercontent.com/106157603/191738347-234a8c93-732d-4401-bffb-9f73ce8a0723.png">

2022-09-25 06:22 UTC, RahulRaj97 requested changes

2022-09-25 06:22 UTC, RahulRaj97 commented on superset-frontend/src/views/CRUD/flash/components/FlashView/FlashView.tsx
> +              : 'NIL'}
Do we need to update the format here as well? As we did in this [PR](https://github.com/careem/superset/pull/76)

2022-09-25 06:22 UTC, RahulRaj97 commented on superset-frontend/src/views/CRUD/flash/components/FlashView/FlashView.tsx
> +              : ''}
Same as above

2022-09-25 06:22 UTC, RahulRaj97 commented on superset-frontend/src/views/CRUD/flash/components/FlashView/FlashView.tsx
> +              : ''}
Same as above.

2022-09-25 06:22 UTC, RahulRaj97 commented on superset-frontend/src/views/CRUD/flash/components/FlashView/FlashView.tsx
> +              : ''}
Same a above

2022-09-25 06:22 UTC, RahulRaj97 commented on superset-frontend/src/views/CRUD/flash/components/FlashView/FlashView.tsx
> +        title={t('Flash Object Information')}
Maybe `Flash Information`

2022-09-26 07:20 UTC, SamraHanifCareem commented on superset-frontend/src/views/CRUD/flash/components/FlashView/FlashView.tsx
> +              : 'NIL'}
Yes, Because we are getting a 24h format date from service and we need to display users in 12hr for e.g (5:00 PM or 5:00 AM

2022-09-26 07:23 UTC, SamraHanifCareem commented on superset-frontend/src/views/CRUD/flash/components/FlashView/FlashView.tsx
> +        title={t('Flash Object Information')}
Modal title changed

2022-09-26 15:49 UTC, RahulRaj97 submitted a review, later dismissed

2022-09-28 06:20 UTC, RahulRaj97 approved these changes

2022-09-28 10:19 UTC, merged