fix: Date 24 hour format issue
careem/superset pull request #76
Opened 2022-09-24 20:05 UTC by SamraHanifCareem

1- While updating flash date format changes to 24 hour format

2022-09-25 06:16 UTC, RahulRaj97 requested changes

2022-09-25 06:16 UTC, RahulRaj97 commented on superset-frontend/src/views/CRUD/flash/components/FlashCreationButton/FlashCreationButton.tsx
> +    console.log('date ==', payload.scheduleStartTime);
Remove `console.log`

2022-09-25 06:16 UTC, RahulRaj97 commented on superset-frontend/src/views/CRUD/flash/components/FlashCreationButton/FlashCreationButton.tsx
> +    console.log('date to send', payload.scheduleStartTime);
Same here `console.log`

2022-09-26 07:28 UTC, j4m4l approved these changes

2022-09-26 07:30 UTC, RahulRaj97 approved these changes

2022-09-26 08:22 UTC, merged