feat(DNA-521): Sql Query Validation
careem/superset pull request #93
Opened 2022-10-13 09:00 UTC by SamraHanifCareem

1- Integration of validation service in Sql Lab and Charts.
2- Stopping propagation of modal while validation of Sql Query.
3- Query validation while updating query in Flash

2022-10-13 14:01 UTC, RahulRaj97 requested changes

2022-10-13 14:01 UTC, RahulRaj97 commented on superset-frontend/src/views/CRUD/flash/components/FlashCreationButton/FlashCreationButton.tsx
> +                validateQuery(sqlToValidate);
Can we extract this in a separate function?

2022-10-19 13:59 UTC, SamraHanifCareem commented on superset-frontend/src/views/CRUD/flash/components/FlashCreationButton/FlashCreationButton.tsx
> +                validateQuery(sqlToValidate);
Changes incorporated

2022-10-22 15:16 UTC, burhanuddinbhopalw approved these changes

2022-10-23 02:51 UTC, j4m4l approved these changes

2022-10-23 14:58 UTC, merged